### ISSUE TITLE
OBJ Load example

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#1]
Hi There,

I like you project very much :-), but i have a hard time to user you latest Blazor3D package.
On the previous Repository, i had it working. But with this one. I need a Example how to load a OBJ file into de viewer.

I came this far.
`ObjGuid = await View3D1.Import3DModelAsync(Import3DFormats.Obj, https://localhost:5001/myimages/example.obj, null, 50);`

a Working Example would be very nice!!

Thanks!

**Comment by simutaroman** [comment]
HI. Your code is correct, but maybe the last argument should be greater. The default delay value is 200ms. If your obj is huge, you must increase this value.
I plan to commit import examples today

**Comment by simutaroman** [comment]
Hi. Obj import example added (see Example 02). You also can try other 3d model format types, like Collada, Fbx, or Gltf. It should work

**Comment by Hypermobile12** [comment]
Thank! this would really help!

**Comment by Hypermobile12** [comment]
Got is Working!

Any Chance to get *.STL  &  *.STP Working as well?

**Comment by simutaroman** [comment]
hmm. loading STL is not a problem for three.js, as I know. I'll add it soon.
But STEP is not such an easy thing. Not sure about it. https://discourse.threejs.org/t/is-there-any-way-to-load-step-file-using-three-js/2842/4

**Comment by simutaroman** [comment]
I've added a basic STL loader (v0.1.6). But still have to add new features like custom materials, or at least colors

**Comment by Hypermobile12** [comment]
Got the STL loader working as well! Great stuff thanks.

- Custom Material would be very great.

- Orthographic/Perspective Camera toggle would be cool too.

**Comment by simutaroman** [comment]
it's planned for the next releases. too many things to do :)

**Comment by Hypermobile12** [comment]
Ortho Camera view is working as well thx.

Love this too. (Grid and the Rotating Camera onstartup)
https://threejs.org/docs/index.html?q=grid#api/en/helpers/GridHelper

https://threejs.org/examples/#webgl_helpers
