### ISSUE TITLE
Realltime updates

### ISSUE THREAD

**Issue by php-gamesontrack** [simutaroman/Blazor3D#10]
Can I persuade you to provide us with a working example of how we can do continous realtime insert/remove/update of objects in a scene?

**Comment by simutaroman** [comment]
those things are under development yet :)
It's one of the urgent things to do

**Comment by php-gamesontrack** [comment]
Can you san anything about the expected time of dellivery? ;-)

**Comment by simutaroman** [comment]
probably, a week or two. Almost have no time for this at the moment

**Comment by simutaroman** [comment]
Hi. I've added the ability to add new objects, delete them and update the scene in "real-time" mode. 
See Example 04 here
This feature is available in v0.1.23
