### ISSUE TITLE
Texture

### ISSUE THREAD

**Issue by TFreudi1** [simutaroman/Blazor3D#13]
Hi, great project ! How can I put a texture (JPG) on a mesh with box or sphere geometry ?

**Comment by simutaroman** [comment]
Hi. It's in future plans. Not developed at the moment

**Comment by TFreudi1** [comment]
OK, than I will check out THREE.js. Neverless really good work  and easy to understand what you did ! Is the source available anywhere ?

**Comment by simutaroman** [comment]
thanks.  it's free, but not open source.

**Comment by Aspyryan** [comment]
Would love to see this! Now I have to use javascript runtime to get it working :(

**Comment by simutaroman** [comment]
OK. will try do it soon

**Comment by simutaroman** [comment]
Since v0.1.24 you can use textures on your objects
also, I've added some basic texture map properties like wraps, wrapt, repeat, offset and rotate
please, let me know if more things required
