### ISSUE TITLE
High CPU Load

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#14]
Hi There, 

I noticed that the GPU load can be pretty high. on animated & non-animated 3D views.
Is there a way. is there a way to limit this Load?

If you really zoom on a 3D View, the Load will rease

**Comment by simutaroman** [comment]
Hi. I do not control this GPU behavior. Probably there are some ThreeJS settings like antialiasing ;). 
Try to use any ThreeJS viewer (like their editor https://threejs.org/editor/) with your models and see the GPU load
