### ISSUE TITLE
how to play animations when i load a model?

### ISSUE THREAD

**Issue by sd797994** [simutaroman/Blazor3D#15]
Hello, I was wondering if I can get and play the animations of a model when using the Import3DModelAsync function, like I can with the threejs loader? like this：
==============================================
var loader = new ColladaLoader();
    loader.load('../models/stormtrooper.dae', function (collada) {
        ...
        animations = collada.animations; 
        avatar = collada.scene;
        mixer = new THREE.AnimationMixer(avatar);
        mixer.clipAction(animations[0]).play();
        scene.add(avatar);
        ...
    });

**Comment by simutaroman** [comment]
Hi. Animations are not implemented yet. But this feature is in the nearest
plans

пт, 23 груд. 2022, 05:44 користувач 下岗的老王 ***@***.***> пише:
