### ISSUE TITLE
no license for the project

### ISSUE THREAD

**Issue by rkblackfire** [simutaroman/Blazor3D#16]
Hello,
thank You for Your work. But at the moment there is no legal way to use Your code.

So would you please add a license to this repository (via repository settings and/or adding a license.md to the root) so that it can be used freely (if this is Your intention).

Lovely would be MIT :-)

**Comment by simutaroman** [comment]
Hi. You can create the pull request and add appropriated licenses here https://github.com/simutaroman/Blazor3D-Core
I have opened the source-code to community, because still don't have much time to develop Blazor3D

**Comment by simutaroman** [comment]
MIT license added
