### ISSUE TITLE
Adding TextGeometry

### ISSUE THREAD

**Issue by jgrules2** [simutaroman/Blazor3D#19]
Hi,

Thanks for this great library. Looking for a straightforward way to implement basic 3d drawing to my blazor server side app, you made this possible.

I was wondering, as i am in the need of identify certain meshes visually, would it be possible to add TextGeometry to the library with not to much effort?

Thanks and keep up the good work

**Comment by simutaroman** [comment]
hi
adding text is in the nearest plans :)

**Comment by jgrules2** [comment]
Hi,

That is good to hear. Any idea when it is on the agenda?

Thanks in advance!

**Comment by simutaroman** [comment]
unfortunately, cannot promise anything now

**Comment by simutaroman** [comment]
it's available in the current release, see https://simutaroman.github.io/Blazor3D/example06
