### ISSUE TITLE
Remove from scene

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#2]
Yet some random questions:

It's possible to Add Geometry or Helpers/Lights etc or Load a STL File.

Predefined Geometry and Helpers can only be set on Init. AFAIK.
While the OBJ-Importer & Stl-Importer can added later to the scene.

-Can you add a Example how to 'Unload/Remove' the Gridhelper/Box/Light etc. (I would like to Toggle a GridHelper)
-Can you add a Example, How to 'Unload/Remove' STL/OBJ File. (just want to know if it's easy possible)
-Can you create a example how to Add predefined Geometry .  (just want to know if it's easy possible)
-Is it relatively easy to make a BoxFeature around a 3DImportFile?

-STL Set Model Color would be very much appreciated!!
-STL Texture would be absolutely my biggest wish!!

EDIT:
Last wish for today 'RenderingsStyle' Environment Map for Reflections. Would be my dream.
https://threejs.org/examples/?q=env#webgl_materials_cubemap_mipmaps

Nice Progress sofar 👍

**Comment by simutaroman** [comment]
some features (like removing objects or adding a bounding box to imported files) are quite easy to implement
other things like texturing an STL are not. As I know, the STL file doesn't contain UV information. So, before applying texture, the UV unwrapping must be done. And it's quite difficult to generate appropriate UV for a variety of possible loaded shapes. Usually it's done manually in special software
In any case, I'll take a look what can be done quiqly

**Comment by Hypermobile12** [comment]
I've looked up what you mean exactly. Youtube Explained that very good how UV-Mapping Works :-) i learned something today.

Maybe then:
Adding Color, and Gloss/Roughness to Step materialProp. Will do the job as well.

**Comment by simutaroman** [comment]
OK. I'll plan this

**Comment by Hypermobile12** [comment]
maybe along with (invisible) reflections maps (to give the Gloss a render look);  

so what i (exactly what's in de picture on the link in the first post of this issue).
the balls with roughness  reflecting the invisible surrounding environment

![example](https://user-images.githubusercontent.com/102034611/181801422-80dd93b0-9f2b-4b5d-9e40-4ae10b31794a.JPG)

**Comment by simutaroman** [comment]
I plan to develop materials and environments a little bit later. First of all, I want to resolve object manipulation problems. 
I want to raise the corresponding event in the Blazor component when the user selects a mesh or helper by mouse or when the object is imported from a file.

**Comment by simutaroman** [comment]
since v0.1.15 you can delete objects by their UUID. Also, you can clear the complete scene. See example02
