### ISSUE TITLE
Grouped object not rendering

### ISSUE THREAD

**Issue by RaminFadaeian** [simutaroman/Blazor3D#20]
First of all thank you very much for awesome library. Well written and easy to use. 
In my application I need to group together several primitive objects into one. I looked at the group definition and its application in Three.js website and it seems that is exactly what I need. There is a Group class in this library as well, However I could not get it to render a Group object using that class. The scene comes back empty. I appreciate any help.

**Comment by simutaroman** [comment]
Hi. 
For now, Group objects in Blazor3D were added only for cases when you import 3D models from external files. In most cases, ThreeJS decomposes such models as Groups. 
So, Blazor3D knows that the imported model is group,  but knows only about Id and name of such a group, not about the children (if I remember correctly),
I think it will be fixed later, but at the moment I can't say when
If you have some time and experience, you can try to help me with this here https://github.com/simutaroman/Blazor3D-Core

**Comment by simutaroman** [comment]
it's fixed in v0.1.28
