### ISSUE TITLE
About EdgesGeometry

### ISSUE THREAD

**Issue by WhyILoveSpringRoll** [simutaroman/Blazor3D#21]
Thank you for creating Blazor3D. I have been experimenting with Blazor3D recently and I need to use EdgesGeometry, but it's currently not available. I was wondering when this feature will be added. I have also been reading the source code and I hope to contribute some code in the future.Thank you.

**Comment by simutaroman** [comment]
Hi. Thanks for your thanks. 
Not sure I will be able to add it soon. It looks like it's pretty easy to do.
In any case, you can find the source code here https://github.com/simutaroman/Blazor3D-Core, it's open-source and under MIT
P.S. If you need this feature very urgent, I'll take a look at weekends

**Comment by WhyILoveSpringRoll** [comment]
Hi,I am trying to implement this feature ,but I am not familiar with JavaScript and there are some issues with the effect. I must manually modify the position of the border to display correctly. I hope you can implement this feature, and I want to learn from it and strive to contribute code as soon as possible.

![1](https://github.com/simutaroman/Blazor3D/assets/14737143/f203eebe-2dcb-4759-bd4e-c32e10ed56ac)
wrong position

![2](https://github.com/simutaroman/Blazor3D/assets/14737143/61d8927e-3139-4c49-87c6-96999eaf1954)

modify 



![3](https://github.com/simutaroman/Blazor3D/assets/14737143/acaf3a4d-0843-4fa2-a8ff-e7bb68a2222e)

correct

**Comment by simutaroman** [comment]
Hi. I've added the basic edges drawing support, 
but be careful it breaks the selection feature. 
At the moment I can't figure out why only mesh edges can be selected, have to do some deep debugging.
But if you don't care about selections, just fill the edges material (see example 1)

**Comment by WhyILoveSpringRoll** [comment]
> Hi. I've added the basic edges drawing support, but be careful it breaks the selection feature. At the moment I can't figure out why only mesh edges can be selected, have to do some deep debugging. But if you don't care about selections, just fill the edges material (see example 1)

thanks a lot
