### ISSUE TITLE
Changing the aspect ratio and size of the Viewer

### ISSUE THREAD

**Issue by shivaramkrs** [simutaroman/Blazor3D#23]
I love Blazor 3D. You have done an amazing work. 

How can I set the height/ width ratio of the Viewer? I tried many things but it doesn't seem to work.

**Comment by danijerez** [comment]
I would also like to know, I am loading a glb file and I cannot center it, the background only accepts hexadecimal colors, without transparency?

**Comment by simutaroman** [comment]
Hi. The intention was to calculate the aspect ratio automatically, depending on document size. It happens on the window resize event. But I didn't consider that the window can remain the same size, but the Viewer parent container can be changed.
It's a bug, and I have to resolve it somehow. I will probably expose the Viewer's resize method or will find another solution...

glb files are loaded by three js glb loader. I just wrapped it. unfortunately, I didn't add functionality to get objects data to .net part after their loading. That wasn't required for my projects and I don't think I will add this soon. You can add it by yourself, code is open-source.

I didn't checked the transparency in background, but I belive you can use CSS rgba function like "rgba(255, 255, 128, .5);"
at least it works with "rgb(255, 255, 128);" as I remember

**Comment by shivaramkrs** [comment]
> Hi. The intention was to calculate the aspect ratio automatically, depending on document size. It happens on the window resize event. But I didn't consider that the window can remain the same size, but the Viewer parent container can be changed. It's a bug, and I have to resolve it somehow. I will probably expose the Viewer's resize method or will find another solution...
> 
> glb files are loaded by three js glb loader. I just wrapped it. unfortunately, I didn't add functionality to get objects data to .net part after their loading. That wasn't required for my projects and I don't think I will add this soon. You can add it by yourself, code is open-source.
> 
> I didn't checked the transparency in background, but I belive you can use CSS rgba function like "rgba(255, 255, 128, .5);" at least it works with "rgb(255, 255, 128);" as I remember

Thank you. Right now I am using fixed height in the CSS
`
#blazorview3d {
    display: flex;
    height: 600px;
}
`
We need transparency in color. For example, I wanted the selected object not to have any color as I am using BoxHelper. I was not able to achieve it. I didn't try rgba function as a string,

**Comment by shivaramkrs** [comment]
@simutaroman What should I run when I resize the canvas to make the objects look in the right aspect ratio? If I change the selection then it is fixing the look.

**Comment by simutaroman** [comment]
> We need transparency in color. For example, I wanted the selected object not to have any color as I am using BoxHelper. I was not able to achieve it. I didn't try rgba function as a string,

At the moment, you cannot control selected object material transparency. Rgba will not help in this case, because for selection only color is taken into account
```
this.INTERSECTED.material.color.setHex(
        new THREE.Color(this.options.viewerSettings.selectedColor).getHex()
      );
```

**Comment by simutaroman** [comment]
> What should I run when I resize the canvas to make the objects look in the right aspect ratio? If I change the selection then it is fixing the look.

At the moment it's a bug. I'll fix it tomorrow, on Monday, 17. As a primitive solution, I'll just expose the Viewer.onResize method to the DonNet part.
Also, I'll try to use https://developer.mozilla.org/en-US/docs/Web/API/ResizeObserver to understand when the canvas or parent container is resized.

**Comment by shivaramkrs** [comment]
> > We need transparency in color. For example, I wanted the selected object not to have any color as I am using BoxHelper. I was not able to achieve it. I didn't try rgba function as a string,
> 
> At the moment, you cannot control selected object material transparency. Rgba will not help in this case, because for selection only color is taken into account
> 
> ```
> this.INTERSECTED.material.color.setHex(
>         new THREE.Color(this.options.viewerSettings.selectedColor).getHex()
>       );
> ```

I did a workaround by selecting the object again artificially. This seemed to work. Removed the highlighted color.

**Comment by simutaroman** [comment]
Hi. I've fixed a bug with the aspect ratio. Now it's recalculated automatically on the container element resizing (where the canvas is placed). Just apply package v.0.1.34 and do "Empty cache and hard reload" in your browser to refresh js

**Comment by shivaramkrs** [comment]
Amazing, thanks a lot for such a fast response.
