### ISSUE TITLE
Basic animations

### ISSUE THREAD

**Issue by danijerez** [simutaroman/Blazor3D#24]
Hello, I have a conceptual idea and I would like to know if I could carry it out with Blazor3d. I have not worked much with the 3d theme, I have a basic gltf model and I would like to do basic programmatic animations, how to rotate certain parts of the model, could this be done? I have seen animations of the entire object, but can it be done on a specific part?

**Comment by simutaroman** [comment]
Hi. I believe it can be done.
But it requires a huge effort to do this.
At the moment, after loading any 3d file into the scene, only JavaScript side (ThreeJS) knows all about the loaded file structure (which node is parent, which are children, their locations, rotations, scaling, etc). It notifies the .Net side about the object id and name, but not about its internal structure.
So, firstly, you need to implement this.
The next thing to do is to implement basic animations (changing positions, rotations, etc)
After that, you can programmatically analyze the loaded model structure and apply required animations for required nodes

It can be done, but at the moment I have no time to do this.

**Comment by danijerez** [comment]
Thanks for answering, I'll be watching the project
