### ISSUE TITLE
Unable to access the scene from the global context within an Interop function

### ISSUE THREAD

**Issue by bryanpdavis** [simutaroman/Blazor3D#25]
Hi there, I'm trying to add 2D labels to my objects within the scene but I have no way of referencing the scene object within my interop function. I think if you export the scene within the Viewer3D object, I think I should be able to access it from the global scope within my function.

Here is what I'm trying to do:

add2DLabel: function (objectName, labelText, layer, scene) {
    console.log("Adding label to scene:" + JSON.stringify(scene));
    let object = scene.getObjectByName(objectName);
    if (object) {
        let labelDiv = document.createElement('div');
        labelDiv.className = 'label';
        labelDiv.textContent = labelText;
        labelDiv.style.backgroundColor = 'transparent';
        console.log("Adding label to scene.");

        let label = new THREE.CSS2DObject(labelDiv);
        label.position.set(0, 0, 0);
        label.center.set(0, 1);
        label.layers.set(layer);

        object.add(label);
    }
    return object;
}

**Comment by simutaroman** [comment]
scene object isn't global. it "leaves" inside the instance the Viewer3D class
```
this.scene = new THREE.Scene();
this.setScene();
```
so, if you call your function inside Viewer3D class, it should be like 
`this.add2DLabel("Obj1", "Some text", this.scene);`

if you define this function in the index.js to call it from .NET part, it should looks like

```
add2DLabel: function (objectName, labelText, layer) {// no scene here
console.log("Adding label to scene:" + JSON.stringify(viewer3d.scene));// scene "lives" in the viewer3d
let object = viewer3d.scene.getObjectByName(objectName);// scene "lives" in the viewer3d
if (object) {
let labelDiv = document.createElement('div');
labelDiv.className = 'label';
labelDiv.textContent = labelText;
labelDiv.style.backgroundColor = 'transparent';
console.log("Adding label to scene.");

    let label = new THREE.CSS2DObject(labelDiv);
    label.position.set(0, 0, 0);
    label.center.set(0, 1);
    label.layers.set(layer);

    object.add(label);
}
return object;
```
because Viewer3D is instantiated in the viewer3d (see loadViewer function)

**Comment by bryanpdavis** [comment]
This is helpful. Still, I'm thinking that I would need to have multiple scenes. Are you able to pass the reference back and forth between .net and js? If not it's like I would want to have the js in a razor.js. I'm guessing that it's not awful to have a few functions in the index, but I was looking to avoid it and in my razor.js I'm not able to see the reference in the window.

**Comment by simutaroman** [comment]
at the moment only one scene is supported. But in theory, multiple scenes can be implemented
_Are you able to pass the reference back and forth between .net and js?_ 
at the moment, no
_If not it's like I would want to have the js in a razor.js._
I don't know the way how to implement this.

In any case, the main idea of this component (as any Blazor component) is to avoid using JS by the end user :) All staff should be done with C#

**Comment by bryanpdavis** [comment]
We are trying your suggestion. I also would prefer to use the C# but I don't see how to add 2D labels through the library. If you would like some work, I have something you can help with? We aren't able to access the viewer3D object within the index.js.

**Comment by simutaroman** [comment]
this task requires adding CSS2DRenderer over WebGLRenderer, 
then it requires defining label property for the Mesh.cs
then it requires adding CSS2DObject child to every Mesh on JS side in MeshBuilder if label property was specified
also we have to control styles of the labels (color, size, etc)
nothing fancy, but it takes time

I cannot promise I will do it soon, because I don't need it for my current projects
can recommend good example here
https://threejs.org/examples/#css2d_label (https://github.com/mrdoob/three.js/blob/master/examples/css2d_label.html)

**Comment by bryanpdavis** [comment]
Do you mean updating the Blazor-Core to do this? Can I hire you? I think your library will definitely help me with my project but I will need to use something else if I can't figure this out. I need to build a scene Manager to manage the objects and make sure the labels face the camera, etc. I can use the 3D labels maybe also, but I need the labels to "lookAt" the camera when the camera moves.

**Comment by simutaroman** [comment]
Yes I mean updating Blazor core to do this. And no, you can not hire me, sorry.
To be honest, i cant recommend using Blazor3D in bisiness project at the moment. And I cannot promise any support for it due the war here in Ukraine
