### ISSUE TITLE
Not able to move the loaded 3D objects

### ISSUE THREAD

**Issue by shivaramkrs** [simutaroman/Blazor3D#26]
I am trying to load 3D assets and position them in the scene. I am not able to change their position. Can you please give a pseudo-code that can do this?

**Comment by simutaroman** [comment]
hi. it's impossible for loaded objects. it's not implemented

**Comment by shivaramkrs** [comment]
What about the animation of loaded 3D objects? Does it play the animations? If this is enabled then you can load the entire scene in Blender and bring it into Blazor3D.

**Comment by simutaroman** [comment]
animations are not supported yet
