### ISSUE TITLE
How to select object via code

### ISSUE THREAD

**Issue by ArnoSchiller** [simutaroman/Blazor3D#32]
Hey, thanks for this great package!

I've got a 3D view and an external button to delete the selected object (like in your examples). When the object is deleted i want to preselect the nearest object in the scene. 
Is there a way to trigger selection (highlighting) in code?

Thanks!

**Comment by simutaroman** [comment]
Hi See Example1
```
 private async Task OnSelectObjectByUUIDClick()
    {
        if (selectObjectGuid.HasValue)
        {
            await View3D1.SelectByUuidAsync(selectObjectGuid.Value);
        }

    }
```

**Comment by ArnoSchiller** [comment]
Ohh sorry, I overlooked that. Thank you very much!
