### ISSUE TITLE
Loadmodel async on Init

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#4]
Hi,

I would like to STL-Load or  OBJ-model  a Model on Page  (without clicking the Button).

Tried a lot, But i'm getting errors.
I had  it working 1 time, But i found out that after a F5 it crashed.

i think the webpage View3D wasn't loaded yet

`Unhandled exception rendering component: Value cannot be null. (Parameter 'jsObjectReference')
      System.ArgumentNullException: Value cannot be null. (Parameter 'jsObjectReference')`

**Comment by simutaroman** [comment]
Could you please provide a source code?

**Comment by Hypermobile12** [comment]
```
    protected override async Task OnAfterRenderAsync(bool firstRender)
    {
        if (firstRender)
        {
            View3D1.ObjectLoaded += OnObjectLoaded;
            await View3D1.Import3DModelAsync(Import3DFormats.Stl, "https://threejs.org/examples/models/stl/ascii/slotted_disk.stl", null);
        }

        await base.OnAfterRenderAsync(firstRender);
    }
```

**Comment by simutaroman** [comment]
Try to call base.OnAfterRenderAsync firstly, then your code.

**Comment by Hypermobile12** [comment]
That actually worked partially.

I've made the 3DViewer a Seperate page...

I call that page with a Iframe view in the other page.

`<iframe src="@Example03Url" title="Example03" ></iframe>`

This method now causes my issues on F5.
I think there is a better way doing this.  i need to Google google  ;-)   





EDIT:

Opening 2 or more time the Same Page gives me the same issue.


So: 1 Blazor Page works.
Adding another Tab with the same viewer..gives issues. 
Seperate Button is Working

on the Try Catch 
e.message:
`Value cannot be null. (Parameter 'jsObjectReference')`

**Comment by simutaroman** [comment]
agree. it's a bug. I'll try to resolve it ASAP

**Comment by Hypermobile12** [comment]
maybe also add a Dispose() example on the pages.

I use something like this. 
Else you have a memory leak, At least that's my experience when you don't unsubscripe to events.

Maybe i forget something to dispose as well.

```
    void IDisposable.Dispose()
    {
        Dispose();
        GC.SuppressFinalize(this);
    }

    public void Dispose()
    {
        View3D1.ClearSceneAsync();
        View3D1.ObjectLoaded -= OnObjectLoaded;
    }
```

**Comment by simutaroman** [comment]
Fixed. Please, use JsModuleLoaded event (see Example02).
Examples are updated with IDisposable and unsubscribing events
Also, a few material properties were added, like metalness, roughness, etc. See Example 01 and https://blazor3d.com/reference/Blazor3D.Materials.MeshStandardMaterial.html

**Comment by Hypermobile12** [comment]
Great stuff :-) Bug Fixed.
