### ISSUE TITLE
Stop Animated Camera

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#5]
What is the correct method to alter some Scene/Camera settings? for example: Toggle Animated Camera
Or is this //ToDo stuff?

`<p><button class="btn btn-primary" @onclick="ToggleCamAnimation">Toggle cam</button> </p>`

```
    private void ToggleCamAnimation()
    {
        Console.WriteLine(View3D1.Camera.AnimateRotationSettings.AnimateRotation);
        View3D1.Camera.AnimateRotationSettings.AnimateRotation = !View3D1.Camera.AnimateRotationSettings.AnimateRotation;
        Console.WriteLine(View3D1.Camera.AnimateRotationSettings.AnimateRotation);
    }
```

**Comment by simutaroman** [comment]
Setting property value to the .NET object doesn't mean it's automatically set to the corresponding JS (three.js) object. It's possible to implement such a feature, but it will be very inefficient. It will produce significant traffic between .NET and JS parts.
Now I'm investigating how to implement this in the best way

**Comment by Hypermobile12** [comment]
it's a 'nice to have'

**Comment by simutaroman** [comment]
as for me, it's a must to be done. But there are so many features to do, so I have to set some priorities.

**Comment by simutaroman** [comment]
I've added the ability to toggle cameras since v0.1.19
It's not exactly what you need, but the first step in that direction
see updated example 3

**Comment by simutaroman** [comment]
The next step is just to update the current camera properties.
Have to think about the proper naming of methods

**Comment by simutaroman** [comment]
fixed by adding new AnimateRotationSettings.StopAnimationOnOrbitControlMove setting in v0.1.20
see Example03

**Comment by Hypermobile12** [comment]
on Example02 Change this: you'll like it

`<Viewer @ref="View3D1" Camera=camera Scene=scene />`
` private Camera camera = new PerspectiveCamera();`

```
protected override Task OnInitializedAsync()
    {
        camera.AnimateRotationSettings = new AnimateRotationSettings(true, 0.4, 0, 0, 1);
        
        etc.
```

**Comment by Hypermobile12** [comment]
> fixed by adding new AnimateRotationSettings.StopAnimationOnOrbitControlMove setting in v0.1.20 see Example03

I don't see the effect descripted. 

Using a TouchScreen or mouse moving the View around, 
But the animation keeps on moving.

**Comment by simutaroman** [comment]
![Screen_Recording__8-4-2022_7-38-20_PM__AdobeExpress](https://user-images.githubusercontent.com/9882179/182905029-77783de3-267a-4176-8fab-1d6d0eff67d5.gif)
try to use hardreload (Ctrl + F5) or empty cache and hard reload from chrome devtools

**Comment by simutaroman** [comment]
did you update the code to the last changes?  you have to see 
private Camera camera = new OrthographicCamera(left: -2, right: 2, top: 2, bottom: -2, zoom:0.5f, near: -10)
        {
            Position = new Vector3(1, 1, 1),
            AnimateRotationSettings = new AnimateRotationSettings(true, 0.1, 0, 0.1, radius: 3)
            {
                StopAnimationOnOrbitControlMove = true
            },
            LookAt = new Vector3(0.5f, 0, 0)
        };

**Comment by Hypermobile12** [comment]
Already tried Ctrl+F5 before asking

Tried Edge; There it worked!
No luck on Chrome (see Message on F12 maybe?)

![chrome-notification](https://user-images.githubusercontent.com/102034611/182916424-3b8fa0b7-847b-49b5-8b8e-6ce286dac315.JPG)

**Comment by Hypermobile12** [comment]
update: in Dev Tool 
Ctrl + RightmouseClick on Reload > Hard reload > no luck

Hard reload + Clear Cache >> I new F5   &  Ctrl+F5    DevTools | Clear Cache+Reload was New4me

**Comment by simutaroman** [comment]
Does it work now? :)

**Comment by Hypermobile12** [comment]
xD yep :-)
