### ISSUE TITLE
Standard mesh for STL import

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#6]
Is that MeshStandardMaterials also appliable on the STL Import?. (at least Color selections)

That would be the last 'must have' (for now) for my project :-)

**Comment by Hypermobile12** [comment]
hmm, i found your //todo in the Code.

;-)

**Comment by simutaroman** [comment]
yes. it's not implemented yet. I'm just thinking about how to do this in a best way :)

**Comment by Hypermobile12** [comment]
Just some Thoughs:

The Method of adding a Sphere or Plane is different than adding STL or OBJ etc.

> 'Predefined' Geometry is set Before init.
> OBJ / STL etc. Geometry must me added After Init.

I think Geometry = Geometry. (some with UV-Mapping some without).

So i though..something like this should work for Both types.
`Scene.Add(Geometry, MeshMaterial)`      STL     OBJ or Sphere or Cone whatever.

**Comment by simutaroman** [comment]
let me explain
**For now**, the complete scene (as a set of predefined shapes) is formed on .NET part before first render. On the first render, the .NET Scene is converted to JSON and is sent to the JS part. On the JS side, JSON is converted to corresponding three.js objects and is added to the three.js scene.
So, order is .NET -> JS (on first render).

Importing files is performed by three.js.  So, the corresponding three.js loader imports your file and adds some objects to the three.js scene. During loading, the JS notifies the .NET part of which objects were loaded. JS sends to the .NET the basic info only, such as imported objects uuid, name, type, and their children. It's because the imported files may be very huge.
So, in this case, the order is JS -> NET (somewhen, when all file content is imported. the corresponding event helps you to know when. And .Net knows only partial info about imported content. For now it's done only for Groups and Meshes)

A little bit later I plan to add new features when you can add new 'predefined' shapes when you want, not before init only.

**Comment by Hypermobile12** [comment]
That makes things way more clear. thx.

Maybe then:
Send from .Net to JS ; Next Material => Grey + Roughness 0.5f.

Then Import3DAsync(file.stl) ....  and that Material is set in JS

**Comment by simutaroman** [comment]
I have added the ability to add custom material on file import. for now, it works for stl only. Hope, this will help you.
Please, see example 2, OnJsModuleLoaded

By the way, it could be nice to mention your project in blazor3d documentation. Hope, you'll send me a link :)

**Comment by Hypermobile12** [comment]
yep that did the Trick for me

fyi: Load OBJ (with Texture failed in this Build)

**Comment by simutaroman** [comment]
thx for testing :)

**Comment by Hypermobile12** [comment]
thx you for Fixing :D

**Comment by simutaroman** [comment]
there will be a texture loading fix for obj in the v0.1.18

**Comment by Hypermobile12** [comment]
1 stl with MeshStandardMaterial
1 obj with a Texturemap

it's Pretty nice. 
Obj is a little harder for me to automate in the 3D program; therefore STL was preferred.
I'm gonna investigate if that OBJ could be my auto-export standard setting.

When the Animated Cam can be manipulated in .NET (after init):
I want my Part Rotating; untill the moment the user is rotate/zoom/pan the model; 
Then i want to stop the animation. But that can wait :-)

Many thanks for the effort!!

![WhatsApp Image 2022-08-03 at 17 31 31](https://user-images.githubusercontent.com/102034611/182648870-f2e20643-f4ff-495c-b70d-635e9f2e7590.jpeg)
![WhatsApp Image 2022-08-03 at 17 31 31 (1)](https://user-images.githubusercontent.com/102034611/182648876-a5564482-8f28-4980-b810-4991d68e85cb.jpeg)

**Comment by Hypermobile12** [comment]
> I have added the ability to add custom material on file import. for now, it works for stl only. Hope, this will help you. Please, see example 2, OnJsModuleLoaded
> 
> By the way, it could be nice to mention your project in blazor3d documentation. Hope, you'll send me a link :)

I'll sent you my viewer as an Example.razor Page to add to your project.
That could be after the holidays

edit: before Holidays...see below

**Comment by Hypermobile12** [comment]
Not the propper way; but here is my example. You may use it in your repo. See Attachment for the Blazor Service Side.

What i like is if you call this URL:

`https://localhost:7264/3DViewer?Article=teapot&Texture=rough-green`

3DViewer picks out Article & Texture.
Check if they Exist
And render them in a Blazor3D window

Now you're able to use it everywhere you have a Browser/other Code. 
`<iframe src="https://localhost:7264/3DViewer?Article=teapot&Texture=rough-green" title="3DView" width="100%" height="1000px" scrolling="no"></iframe>`


The other thing i Like: 
2 Files The 3DViewer.Razor & 3DViewer.Razor.Cs will work together.
Having 1 file for layout 1 file for functions.

[Blazor3D.Examples.Server.zip](https://github.com/simutaroman/Blazor3D/files/9253897/Blazor3D.Examples.Server.zip)

**Comment by simutaroman** [comment]
Interesting approach, like it
there are pros and cons, but it's very, very interesting

not sure GC.SuppressFinalize is required here https://stackoverflow.com/questions/151051/when-should-i-use-gc-suppressfinalize

**Comment by Hypermobile12** [comment]
About GC.SuppressFinalize

I've had big memory leak issues.
Fixed it with unsubscribe /dispose, 
It doesn't Hurt at least.

My main blazor app has 500 instanties of pages 8 clients in sync. Those instances need to be trashed after beiing used. Else the signalR is slow.

The viewer is independent from the other complex pages.

That is my biggest advantage.


On my main app, i don't have a navigatie bar as well.


Nice you like my approach :)

**Comment by Hypermobile12** [comment]
What i do is hosting the Linux Share on to Http:// 

For a ServerSide Blazor; you can add a fileserver like this in Startup.CS somewhere in 
`    public void Configure(IApplicationBuilder app, IWebHostEnvironment env)`

`        app.UseStaticFiles(new StaticFileOptions()
        {
            FileProvider = new PhysicalFileProvider(@"/var/Models"), 
            ServeUnknownFileTypes = true,
            RequestPath = new PathString("/Models")
        });`
