### ISSUE TITLE
antialias possible?

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#7]
Hi there,

https://threejs.org/docs/#api/en/renderers/WebGLRenderer.antialias 

Antialias - whether to perform antialiasing. Default is false.

Can you port this to Blazor3D?

**Comment by simutaroman** [comment]
Hi. I'll take a look

**Comment by simutaroman** [comment]
Hi. I've added antialiasing in v0.1.21
see example01
```
 private ViewerSettings settings = new ViewerSettings()
        {
            ContainerId = "example1",
            CanSelect = true,// default is false
            SelectedColor = "black",
            WebGLRendererSettings = new WebGLRendererSettings
            {
                Antialias = true
            }
        };
```
Thinking about making this option true by default... What do you think about this?

**Comment by Hypermobile12** [comment]
I think that's a good thing.

1 step closer in the right direction for higher quality display. Towards  Rendering ;-) 

Material Reflections/surrounding reflexions would nice to be next?

**Comment by Hypermobile12** [comment]
Display is way Better now :-)

**Comment by simutaroman** [comment]
antialiasing is on by default since v0.1.22

**Comment by simutaroman** [comment]
I'll think about reflections and environment maps :)
