### ISSUE TITLE
Positioning Camera's is very difficult

### ISSUE THREAD

**Issue by Hypermobile12** [simutaroman/Blazor3D#9]
Last week, it took me multiple hours to Exactly setup the Camera angle for a Model.

It's Try Reload Error.

Is there a way, that the Actual Camera Angle/all Useful params are dropped in the Console.
So it's possible to set the angle exactly as you want.

Grab the Vector / LookAtVector Zoom / Scale etc from the Console

**Comment by simutaroman** [comment]
OK. I'll add a special method to display this info on demand.

**Comment by simutaroman** [comment]
Hi. I've added a new method Viewer.ShowCurrentCameraInfo() in v0.1.22.
See Example3 for more info
It prints the current camera and orbit control objects into the browser console.
Hope this will help you
